/**
 * Reflects migrations 001–076 (Sprint 25.1)
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | {[key: string]: Json | undefined}
  | Json[];

export type Database = {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          legal_name: string;
          trade_name: string | null;
          tax_id: string;
          slug: string;
          email: string;
          phone: string | null;
          whatsapp: string | null;
          website: string | null;
          state_registration: string | null;
          municipal_registration: string | null;
          address_street: string | null;
          address_number: string | null;
          address_complement: string | null;
          address_neighborhood: string | null;
          address_city: string | null;
          address_state: string | null;
          address_zip: string | null;
          address_country: string | null;
          logo_url: string | null;
          settings: Json;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          provision_status: 'pending' | 'in_progress' | 'completed' | 'error';
          provisioned_at: string | null;
          provision_error: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          legal_name: string;
          trade_name?: string | null;
          tax_id: string;
          slug: string;
          email: string;
          phone?: string | null;
          whatsapp?: string | null;
          website?: string | null;
          state_registration?: string | null;
          municipal_registration?: string | null;
          address_street?: string | null;
          address_number?: string | null;
          address_complement?: string | null;
          address_neighborhood?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_zip?: string | null;
          address_country?: string | null;
          logo_url?: string | null;
          settings?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          provision_status?: 'pending' | 'in_progress' | 'completed' | 'error';
          provisioned_at?: string | null;
          provision_error?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          legal_name?: string;
          trade_name?: string | null;
          tax_id?: string;
          slug?: string;
          email?: string;
          phone?: string | null;
          whatsapp?: string | null;
          website?: string | null;
          state_registration?: string | null;
          municipal_registration?: string | null;
          address_street?: string | null;
          address_number?: string | null;
          address_complement?: string | null;
          address_neighborhood?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_zip?: string | null;
          address_country?: string | null;
          logo_url?: string | null;
          settings?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          provision_status?: 'pending' | 'in_progress' | 'completed' | 'error';
          provisioned_at?: string | null;
          provision_error?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      branches: {
        Row: {
          id: string;
          company_id: string;
          code: string;
          name: string;
          tax_id: string | null;
          is_headquarters: boolean;
          address_street: string | null;
          address_city: string | null;
          address_state: string | null;
          address_zip: string | null;
          phone: string | null;
          responsible_name: string | null;
          metadata: Json;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          code: string;
          name: string;
          tax_id?: string | null;
          is_headquarters?: boolean;
          address_street?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_zip?: string | null;
          phone?: string | null;
          responsible_name?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          code?: string;
          name?: string;
          tax_id?: string | null;
          is_headquarters?: boolean;
          address_street?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_zip?: string | null;
          phone?: string | null;
          responsible_name?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          avatar_url: string | null;
          phone: string | null;
          preferences: Json;
          last_login_at: string | null;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name: string;
          email: string;
          avatar_url?: string | null;
          phone?: string | null;
          preferences?: Json;
          last_login_at?: string | null;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          email?: string;
          avatar_url?: string | null;
          phone?: string | null;
          preferences?: Json;
          last_login_at?: string | null;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      permissions: {
        Row: {
          id: string;
          code: string;
          resource: string;
          action: string;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          resource: string;
          action: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          resource?: string;
          action?: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      roles: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          description: string | null;
          is_system: boolean;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          description?: string | null;
          is_system?: boolean;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          description?: string | null;
          is_system?: boolean;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          role_id: string;
          permission_id: string;
          company_id: string;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          role_id: string;
          permission_id: string;
          company_id: string;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          role_id?: string;
          permission_id?: string;
          company_id?: string;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      company_members: {
        Row: {
          id: string;
          company_id: string;
          profile_id: string;
          role_id: string;
          default_branch_id: string | null;
          invited_at: string | null;
          accepted_at: string | null;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          profile_id: string;
          role_id: string;
          default_branch_id?: string | null;
          invited_at?: string | null;
          accepted_at?: string | null;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          profile_id?: string;
          role_id?: string;
          default_branch_id?: string | null;
          invited_at?: string | null;
          accepted_at?: string | null;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      portal_users: {
        Row: {
          id: string;
          profile_id: string;
          role: 'OWNER' | 'SUPPORT' | 'FINANCE';
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          role: 'OWNER' | 'SUPPORT' | 'FINANCE';
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          role?: 'OWNER' | 'SUPPORT' | 'FINANCE';
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      portal_audit_logs: {
        Row: {
          id: string;
          action: 'login' | 'logout' | 'company_create' | 'company_update' | 'company_provision' | 'company_delete' | 'password_reset' | 'user_create' | 'user_update' | 'user_role_change' | 'user_activate' | 'user_deactivate' | 'plan_change' | 'company_suspend' | 'company_reactivate' | 'settings_update';
          actor_profile_id: string | null;
          actor_email: string | null;
          target_type: string | null;
          target_id: string | null;
          target_label: string | null;
          metadata: Json;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          action: 'login' | 'logout' | 'company_create' | 'company_update' | 'company_provision' | 'company_delete' | 'password_reset' | 'user_create' | 'user_update' | 'user_role_change' | 'user_activate' | 'user_deactivate' | 'plan_change' | 'company_suspend' | 'company_reactivate' | 'settings_update';
          actor_profile_id?: string | null;
          actor_email?: string | null;
          target_type?: string | null;
          target_id?: string | null;
          target_label?: string | null;
          metadata?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          action?: 'login' | 'logout' | 'company_create' | 'company_update' | 'company_provision' | 'company_delete' | 'password_reset' | 'user_create' | 'user_update' | 'user_role_change' | 'user_activate' | 'user_deactivate' | 'plan_change' | 'company_suspend' | 'company_reactivate' | 'settings_update';
          actor_profile_id?: string | null;
          actor_email?: string | null;
          target_type?: string | null;
          target_id?: string | null;
          target_label?: string | null;
          metadata?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      platform_settings: {
        Row: {
          id: string;
          platform_name: string;
          logo_url: string | null;
          favicon_url: string | null;
          public_url: string | null;
          smtp_config: Json;
          sender_email: string | null;
          session_timeout_minutes: number;
          password_policy: Json;
          max_upload_mb: number;
          integrations: Json;
          feature_flags: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          platform_name?: string;
          logo_url?: string | null;
          favicon_url?: string | null;
          public_url?: string | null;
          smtp_config?: Json;
          sender_email?: string | null;
          session_timeout_minutes?: number;
          password_policy?: Json;
          max_upload_mb?: number;
          integrations?: Json;
          feature_flags?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          platform_name?: string;
          logo_url?: string | null;
          favicon_url?: string | null;
          public_url?: string | null;
          smtp_config?: Json;
          sender_email?: string | null;
          session_timeout_minutes?: number;
          password_policy?: Json;
          max_upload_mb?: number;
          integrations?: Json;
          feature_flags?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      vision_providers: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          provider_name: 'openai' | 'google' | 'azure' | 'aws' | 'anthropic' | 'custom';
          kind: 'ocr' | 'image_analysis' | 'document_vision' | 'object_detection' | 'multimodal' | 'custom';
          model: string | null;
          config: Json;
          is_default: boolean;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          metadata: Json;
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          provider_name: 'openai' | 'google' | 'azure' | 'aws' | 'anthropic' | 'custom';
          kind: 'ocr' | 'image_analysis' | 'document_vision' | 'object_detection' | 'multimodal' | 'custom';
          model?: string | null;
          config?: Json;
          is_default?: boolean;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          metadata?: Json;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          provider_name?: 'openai' | 'google' | 'azure' | 'aws' | 'anthropic' | 'custom';
          kind?: 'ocr' | 'image_analysis' | 'document_vision' | 'object_detection' | 'multimodal' | 'custom';
          model?: string | null;
          config?: Json;
          is_default?: boolean;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          metadata?: Json;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      vehicles: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          plate: string;
          fleet_number: string | null;
          vehicle_type: string;
          body_type: string | null;
          brand: string | null;
          model: string | null;
          year: number | null;
          renavam: string | null;
          chassis: string | null;
          color: string | null;
          fuel_type: 'diesel' | 'gasoline' | 'ethanol' | 'flex' | 'gnv' | 'electric' | 'hybrid' | 'other' | null;
          load_capacity_kg: number | null;
          gross_weight_kg: number | null;
          tare_kg: number | null;
          axles: number | null;
          initial_odometer_km: number;
          current_odometer_km: number;
          hour_meter: number | null;
          asset_status: 'active' | 'maintenance' | 'inactive' | 'sold';
          photo_url: string | null;
          crlv_url: string | null;
          photo_storage_path: string | null;
          crlv_storage_path: string | null;
          external_id: string | null;
          integration_source: string | null;
          metadata: Json;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          plate: string;
          fleet_number?: string | null;
          vehicle_type: string;
          body_type?: string | null;
          brand?: string | null;
          model?: string | null;
          year?: number | null;
          renavam?: string | null;
          chassis?: string | null;
          color?: string | null;
          fuel_type?: 'diesel' | 'gasoline' | 'ethanol' | 'flex' | 'gnv' | 'electric' | 'hybrid' | 'other' | null;
          load_capacity_kg?: number | null;
          gross_weight_kg?: number | null;
          tare_kg?: number | null;
          axles?: number | null;
          initial_odometer_km?: number;
          current_odometer_km?: number;
          hour_meter?: number | null;
          asset_status?: 'active' | 'maintenance' | 'inactive' | 'sold';
          photo_url?: string | null;
          crlv_url?: string | null;
          photo_storage_path?: string | null;
          crlv_storage_path?: string | null;
          external_id?: string | null;
          integration_source?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          plate?: string;
          fleet_number?: string | null;
          vehicle_type?: string;
          body_type?: string | null;
          brand?: string | null;
          model?: string | null;
          year?: number | null;
          renavam?: string | null;
          chassis?: string | null;
          color?: string | null;
          fuel_type?: 'diesel' | 'gasoline' | 'ethanol' | 'flex' | 'gnv' | 'electric' | 'hybrid' | 'other' | null;
          load_capacity_kg?: number | null;
          gross_weight_kg?: number | null;
          tare_kg?: number | null;
          axles?: number | null;
          initial_odometer_km?: number;
          current_odometer_km?: number;
          hour_meter?: number | null;
          asset_status?: 'active' | 'maintenance' | 'inactive' | 'sold';
          photo_url?: string | null;
          crlv_url?: string | null;
          photo_storage_path?: string | null;
          crlv_storage_path?: string | null;
          external_id?: string | null;
          integration_source?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      vehicle_history: {
        Row: {
          id: string;
          company_id: string;
          vehicle_id: string;
          action: string;
          changes: Json;
          previous_asset_status: 'active' | 'maintenance' | 'inactive' | 'sold' | null;
          new_asset_status: 'active' | 'maintenance' | 'inactive' | 'sold' | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          vehicle_id: string;
          action: string;
          changes?: Json;
          previous_asset_status?: 'active' | 'maintenance' | 'inactive' | 'sold' | null;
          new_asset_status?: 'active' | 'maintenance' | 'inactive' | 'sold' | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          vehicle_id?: string;
          action?: string;
          changes?: Json;
          previous_asset_status?: 'active' | 'maintenance' | 'inactive' | 'sold' | null;
          new_asset_status?: 'active' | 'maintenance' | 'inactive' | 'sold' | null;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      vehicle_documents: {
        Row: {
          id: string;
          company_id: string;
          vehicle_id: string;
          name: string;
          file_url: string;
          storage_path: string | null;
          document_type: string;
          mime_type: string | null;
          file_size: number | null;
          created_at: string;
          deleted_at: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          vehicle_id: string;
          name: string;
          file_url: string;
          storage_path?: string | null;
          document_type?: string;
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          vehicle_id?: string;
          name?: string;
          file_url?: string;
          storage_path?: string | null;
          document_type?: string;
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
        };
        Relationships: [];
      };
      drivers: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          name: string;
          cpf: string;
          rg: string | null;
          cnh_number: string;
          license_category: 'A' | 'B' | 'C' | 'D' | 'E' | 'AB' | 'AC' | 'AD' | 'AE';
          license_issued_at: string | null;
          license_expires_at: string | null;
          ear: boolean;
          birth_date: string | null;
          phone: string | null;
          whatsapp: string | null;
          email: string | null;
          address: string | null;
          zip_code: string | null;
          city: string | null;
          state: string | null;
          notes: string | null;
          photo_url: string | null;
          photo_storage_path: string | null;
          operational_status: 'active' | 'inactive';
          hired_at: string | null;
          terminated_at: string | null;
          contract_type: 'clt' | 'pj' | 'autonomo' | 'agregado' | 'terceiro' | null;
          emergency_contact: string | null;
          metadata: Json;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id: string | null;
          integration_source: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          name: string;
          cpf: string;
          rg?: string | null;
          cnh_number: string;
          license_category: 'A' | 'B' | 'C' | 'D' | 'E' | 'AB' | 'AC' | 'AD' | 'AE';
          license_issued_at?: string | null;
          license_expires_at?: string | null;
          ear?: boolean;
          birth_date?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          address?: string | null;
          zip_code?: string | null;
          city?: string | null;
          state?: string | null;
          notes?: string | null;
          photo_url?: string | null;
          photo_storage_path?: string | null;
          operational_status?: 'active' | 'inactive';
          hired_at?: string | null;
          terminated_at?: string | null;
          contract_type?: 'clt' | 'pj' | 'autonomo' | 'agregado' | 'terceiro' | null;
          emergency_contact?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          name?: string;
          cpf?: string;
          rg?: string | null;
          cnh_number?: string;
          license_category?: 'A' | 'B' | 'C' | 'D' | 'E' | 'AB' | 'AC' | 'AD' | 'AE';
          license_issued_at?: string | null;
          license_expires_at?: string | null;
          ear?: boolean;
          birth_date?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          address?: string | null;
          zip_code?: string | null;
          city?: string | null;
          state?: string | null;
          notes?: string | null;
          photo_url?: string | null;
          photo_storage_path?: string | null;
          operational_status?: 'active' | 'inactive';
          hired_at?: string | null;
          terminated_at?: string | null;
          contract_type?: 'clt' | 'pj' | 'autonomo' | 'agregado' | 'terceiro' | null;
          emergency_contact?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      driver_history: {
        Row: {
          id: string;
          company_id: string;
          driver_id: string;
          action: string;
          changes: Json;
          previous_operational_status: 'active' | 'inactive' | null;
          new_operational_status: 'active' | 'inactive' | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          driver_id: string;
          action: string;
          changes?: Json;
          previous_operational_status?: 'active' | 'inactive' | null;
          new_operational_status?: 'active' | 'inactive' | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          driver_id?: string;
          action?: string;
          changes?: Json;
          previous_operational_status?: 'active' | 'inactive' | null;
          new_operational_status?: 'active' | 'inactive' | null;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      driver_documents: {
        Row: {
          id: string;
          company_id: string;
          driver_id: string;
          name: string;
          file_url: string;
          storage_path: string | null;
          document_type: 'photo' | 'cnh_front' | 'cnh_back' | 'proof' | 'aso' | 'document';
          mime_type: string | null;
          file_size: number | null;
          created_at: string;
          deleted_at: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          driver_id: string;
          name: string;
          file_url: string;
          storage_path?: string | null;
          document_type?: 'photo' | 'cnh_front' | 'cnh_back' | 'proof' | 'aso' | 'document';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          driver_id?: string;
          name?: string;
          file_url?: string;
          storage_path?: string | null;
          document_type?: 'photo' | 'cnh_front' | 'cnh_back' | 'proof' | 'aso' | 'document';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
        };
        Relationships: [];
      };
      trips: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          trip_number: string;
          trip_status: 'planned' | 'scheduled' | 'loading' | 'in_progress' | 'delivering' | 'waiting' | 'completed' | 'cancelled' | 'returned';
          driver_id: string | null;
          vehicle_id: string | null;
          client_name: string | null;
          contract_reference: string | null;
          origin: string | null;
          destination: string | null;
          route: string | null;
          initial_odometer_km: number | null;
          final_odometer_km: number | null;
          initial_hour_meter: number | null;
          final_hour_meter: number | null;
          departed_at: string | null;
          arrived_at: string | null;
          weight_kg: number | null;
          volume_m3: number | null;
          cargo_type: string | null;
          notes: string | null;
          responsible: string | null;
          metadata: Json;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id: string | null;
          integration_source: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          trip_number: string;
          trip_status?: 'planned' | 'scheduled' | 'loading' | 'in_progress' | 'delivering' | 'waiting' | 'completed' | 'cancelled' | 'returned';
          driver_id?: string | null;
          vehicle_id?: string | null;
          client_name?: string | null;
          contract_reference?: string | null;
          origin?: string | null;
          destination?: string | null;
          route?: string | null;
          initial_odometer_km?: number | null;
          final_odometer_km?: number | null;
          initial_hour_meter?: number | null;
          final_hour_meter?: number | null;
          departed_at?: string | null;
          arrived_at?: string | null;
          weight_kg?: number | null;
          volume_m3?: number | null;
          cargo_type?: string | null;
          notes?: string | null;
          responsible?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          trip_number?: string;
          trip_status?: 'planned' | 'scheduled' | 'loading' | 'in_progress' | 'delivering' | 'waiting' | 'completed' | 'cancelled' | 'returned';
          driver_id?: string | null;
          vehicle_id?: string | null;
          client_name?: string | null;
          contract_reference?: string | null;
          origin?: string | null;
          destination?: string | null;
          route?: string | null;
          initial_odometer_km?: number | null;
          final_odometer_km?: number | null;
          initial_hour_meter?: number | null;
          final_hour_meter?: number | null;
          departed_at?: string | null;
          arrived_at?: string | null;
          weight_kg?: number | null;
          volume_m3?: number | null;
          cargo_type?: string | null;
          notes?: string | null;
          responsible?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      trip_history: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          trip_id: string;
          action: string;
          changes: Json;
          previous_trip_status: 'planned' | 'scheduled' | 'loading' | 'in_progress' | 'delivering' | 'waiting' | 'completed' | 'cancelled' | 'returned' | null;
          new_trip_status: 'planned' | 'scheduled' | 'loading' | 'in_progress' | 'delivering' | 'waiting' | 'completed' | 'cancelled' | 'returned' | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          trip_id: string;
          action: string;
          changes?: Json;
          previous_trip_status?: 'planned' | 'scheduled' | 'loading' | 'in_progress' | 'delivering' | 'waiting' | 'completed' | 'cancelled' | 'returned' | null;
          new_trip_status?: 'planned' | 'scheduled' | 'loading' | 'in_progress' | 'delivering' | 'waiting' | 'completed' | 'cancelled' | 'returned' | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          trip_id?: string;
          action?: string;
          changes?: Json;
          previous_trip_status?: 'planned' | 'scheduled' | 'loading' | 'in_progress' | 'delivering' | 'waiting' | 'completed' | 'cancelled' | 'returned' | null;
          new_trip_status?: 'planned' | 'scheduled' | 'loading' | 'in_progress' | 'delivering' | 'waiting' | 'completed' | 'cancelled' | 'returned' | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      trip_documents: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          trip_id: string;
          name: string;
          file_url: string;
          storage_path: string | null;
          document_type: 'cte' | 'mdfe' | 'nfe' | 'canhoto' | 'photo' | 'receipt' | 'checklist' | 'other';
          mime_type: string | null;
          file_size: number | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          trip_id: string;
          name: string;
          file_url: string;
          storage_path?: string | null;
          document_type?: 'cte' | 'mdfe' | 'nfe' | 'canhoto' | 'photo' | 'receipt' | 'checklist' | 'other';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          trip_id?: string;
          name?: string;
          file_url?: string;
          storage_path?: string | null;
          document_type?: 'cte' | 'mdfe' | 'nfe' | 'canhoto' | 'photo' | 'receipt' | 'checklist' | 'other';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      trip_occurrences: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          trip_id: string;
          occurrence_type: 'delay' | 'breakdown' | 'accident' | 'fine' | 'redelivery' | 'return' | 'missing_document' | 'other';
          description: string | null;
          occurred_at: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          trip_id: string;
          occurrence_type: 'delay' | 'breakdown' | 'accident' | 'fine' | 'redelivery' | 'return' | 'missing_document' | 'other';
          description?: string | null;
          occurred_at?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          trip_id?: string;
          occurrence_type?: 'delay' | 'breakdown' | 'accident' | 'fine' | 'redelivery' | 'return' | 'missing_document' | 'other';
          description?: string | null;
          occurred_at?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      trip_checklists: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          trip_id: string;
          tires_ok: boolean | null;
          headlights_ok: boolean | null;
          brakes_ok: boolean | null;
          documentation_ok: boolean | null;
          fuel_ok: boolean | null;
          odometer_reading: number | null;
          hour_meter_reading: number | null;
          photo_urls: Json;
          signature_url: string | null;
          notes: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          trip_id: string;
          tires_ok?: boolean | null;
          headlights_ok?: boolean | null;
          brakes_ok?: boolean | null;
          documentation_ok?: boolean | null;
          fuel_ok?: boolean | null;
          odometer_reading?: number | null;
          hour_meter_reading?: number | null;
          photo_urls?: Json;
          signature_url?: string | null;
          notes?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          trip_id?: string;
          tires_ok?: boolean | null;
          headlights_ok?: boolean | null;
          brakes_ok?: boolean | null;
          documentation_ok?: boolean | null;
          fuel_ok?: boolean | null;
          odometer_reading?: number | null;
          hour_meter_reading?: number | null;
          photo_urls?: Json;
          signature_url?: string | null;
          notes?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      trip_expenses: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          trip_id: string;
          expense_type: 'toll' | 'food' | 'lodging' | 'tire_shop' | 'maintenance' | 'other';
          amount: number;
          currency: string;
          description: string | null;
          expense_date: string;
          receipt_url: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          trip_id: string;
          expense_type: 'toll' | 'food' | 'lodging' | 'tire_shop' | 'maintenance' | 'other';
          amount?: number;
          currency?: string;
          description?: string | null;
          expense_date?: string;
          receipt_url?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          trip_id?: string;
          expense_type?: 'toll' | 'food' | 'lodging' | 'tire_shop' | 'maintenance' | 'other';
          amount?: number;
          currency?: string;
          description?: string | null;
          expense_date?: string;
          receipt_url?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      trip_stops: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          trip_id: string;
          client_name: string | null;
          stop_date: string | null;
          stop_time: string | null;
          latitude: number | null;
          longitude: number | null;
          stopped_minutes: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          trip_id: string;
          client_name?: string | null;
          stop_date?: string | null;
          stop_time?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          stopped_minutes?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          trip_id?: string;
          client_name?: string | null;
          stop_date?: string | null;
          stop_time?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          stopped_minutes?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      trip_locations: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          trip_id: string;
          latitude: number;
          longitude: number;
          recorded_at: string;
          speed_kmh: number | null;
          accuracy_m: number | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          trip_id: string;
          latitude: number;
          longitude: number;
          recorded_at?: string;
          speed_kmh?: number | null;
          accuracy_m?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          trip_id?: string;
          latitude?: number;
          longitude?: number;
          recorded_at?: string;
          speed_kmh?: number | null;
          accuracy_m?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      fuel_records: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string;
          driver_id: string;
          trip_id: string | null;
          station_name: string | null;
          station_brand: string | null;
          city: string | null;
          state: string | null;
          fueled_at: string;
          fuel_type: 'diesel' | 'gasoline' | 'ethanol' | 'flex' | 'gnv' | 'electric' | 'hybrid' | 'other';
          quantity_liters: number;
          price_per_liter: number;
          total_amount: number;
          odometer_km: number | null;
          hour_meter: number | null;
          km_traveled: number | null;
          consumption_l_per_100km: number | null;
          km_per_liter: number | null;
          cost_per_km: number | null;
          autonomy_km: number | null;
          notes: string | null;
          responsible: string | null;
          is_inconsistent: boolean;
          inconsistency_flags: Database['public']['Enums']['fuel_inconsistency_flag'][];
          metadata: Json;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id: string | null;
          integration_source: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id: string;
          driver_id: string;
          trip_id?: string | null;
          station_name?: string | null;
          station_brand?: string | null;
          city?: string | null;
          state?: string | null;
          fueled_at?: string;
          fuel_type: 'diesel' | 'gasoline' | 'ethanol' | 'flex' | 'gnv' | 'electric' | 'hybrid' | 'other';
          quantity_liters: number;
          price_per_liter: number;
          total_amount: number;
          odometer_km?: number | null;
          hour_meter?: number | null;
          km_traveled?: number | null;
          consumption_l_per_100km?: number | null;
          km_per_liter?: number | null;
          cost_per_km?: number | null;
          autonomy_km?: number | null;
          notes?: string | null;
          responsible?: string | null;
          is_inconsistent?: boolean;
          inconsistency_flags?: Database['public']['Enums']['fuel_inconsistency_flag'][];
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string;
          driver_id?: string;
          trip_id?: string | null;
          station_name?: string | null;
          station_brand?: string | null;
          city?: string | null;
          state?: string | null;
          fueled_at?: string;
          fuel_type?: 'diesel' | 'gasoline' | 'ethanol' | 'flex' | 'gnv' | 'electric' | 'hybrid' | 'other';
          quantity_liters?: number;
          price_per_liter?: number;
          total_amount?: number;
          odometer_km?: number | null;
          hour_meter?: number | null;
          km_traveled?: number | null;
          consumption_l_per_100km?: number | null;
          km_per_liter?: number | null;
          cost_per_km?: number | null;
          autonomy_km?: number | null;
          notes?: string | null;
          responsible?: string | null;
          is_inconsistent?: boolean;
          inconsistency_flags?: Database['public']['Enums']['fuel_inconsistency_flag'][];
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      fuel_history: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          driver_id: string | null;
          trip_id: string | null;
          fuel_record_id: string;
          action: string;
          changes: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          fuel_record_id: string;
          action: string;
          changes?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          fuel_record_id?: string;
          action?: string;
          changes?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      fuel_documents: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          driver_id: string | null;
          trip_id: string | null;
          fuel_record_id: string;
          name: string;
          file_url: string;
          storage_path: string | null;
          document_type: 'invoice' | 'receipt' | 'proof' | 'pump_photo' | 'other';
          mime_type: string | null;
          file_size: number | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          fuel_record_id: string;
          name: string;
          file_url: string;
          storage_path?: string | null;
          document_type?: 'invoice' | 'receipt' | 'proof' | 'pump_photo' | 'other';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          fuel_record_id?: string;
          name?: string;
          file_url?: string;
          storage_path?: string | null;
          document_type?: 'invoice' | 'receipt' | 'proof' | 'pump_photo' | 'other';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      maintenance_records: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string;
          driver_id: string | null;
          trip_id: string | null;
          maintenance_type: 'preventive' | 'corrective' | 'emergency' | 'warranty' | 'review' | 'oil_change' | 'brakes' | 'suspension' | 'engine' | 'electrical' | 'cooling' | 'transmission' | 'tires' | 'other';
          priority: 'low' | 'medium' | 'high' | 'critical';
          maintenance_status: 'open' | 'in_progress' | 'waiting_parts' | 'completed' | 'cancelled';
          supplier: string | null;
          workshop: string | null;
          opened_at: string;
          completed_at: string | null;
          odometer_km: number | null;
          hour_meter: number | null;
          downtime_hours: number | null;
          description: string | null;
          diagnosis: string | null;
          solution: string | null;
          notes: string | null;
          estimated_amount: number | null;
          final_amount: number | null;
          parts_total: number;
          services_total: number;
          total_cost: number;
          cost_per_km: number | null;
          responsible: string | null;
          metadata: Json;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id: string | null;
          integration_source: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id: string;
          driver_id?: string | null;
          trip_id?: string | null;
          maintenance_type: 'preventive' | 'corrective' | 'emergency' | 'warranty' | 'review' | 'oil_change' | 'brakes' | 'suspension' | 'engine' | 'electrical' | 'cooling' | 'transmission' | 'tires' | 'other';
          priority?: 'low' | 'medium' | 'high' | 'critical';
          maintenance_status?: 'open' | 'in_progress' | 'waiting_parts' | 'completed' | 'cancelled';
          supplier?: string | null;
          workshop?: string | null;
          opened_at?: string;
          completed_at?: string | null;
          odometer_km?: number | null;
          hour_meter?: number | null;
          downtime_hours?: number | null;
          description?: string | null;
          diagnosis?: string | null;
          solution?: string | null;
          notes?: string | null;
          estimated_amount?: number | null;
          final_amount?: number | null;
          parts_total?: number;
          services_total?: number;
          total_cost?: number;
          cost_per_km?: number | null;
          responsible?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string;
          driver_id?: string | null;
          trip_id?: string | null;
          maintenance_type?: 'preventive' | 'corrective' | 'emergency' | 'warranty' | 'review' | 'oil_change' | 'brakes' | 'suspension' | 'engine' | 'electrical' | 'cooling' | 'transmission' | 'tires' | 'other';
          priority?: 'low' | 'medium' | 'high' | 'critical';
          maintenance_status?: 'open' | 'in_progress' | 'waiting_parts' | 'completed' | 'cancelled';
          supplier?: string | null;
          workshop?: string | null;
          opened_at?: string;
          completed_at?: string | null;
          odometer_km?: number | null;
          hour_meter?: number | null;
          downtime_hours?: number | null;
          description?: string | null;
          diagnosis?: string | null;
          solution?: string | null;
          notes?: string | null;
          estimated_amount?: number | null;
          final_amount?: number | null;
          parts_total?: number;
          services_total?: number;
          total_cost?: number;
          cost_per_km?: number | null;
          responsible?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      maintenance_history: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          driver_id: string | null;
          trip_id: string | null;
          maintenance_record_id: string;
          action: string;
          changes: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          maintenance_record_id: string;
          action: string;
          changes?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          maintenance_record_id?: string;
          action?: string;
          changes?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      maintenance_documents: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          driver_id: string | null;
          trip_id: string | null;
          maintenance_record_id: string;
          name: string;
          file_url: string;
          storage_path: string | null;
          document_type: 'budget' | 'invoice' | 'photo' | 'service_order' | 'report' | 'other';
          mime_type: string | null;
          file_size: number | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          maintenance_record_id: string;
          name: string;
          file_url: string;
          storage_path?: string | null;
          document_type?: 'budget' | 'invoice' | 'photo' | 'service_order' | 'report' | 'other';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          maintenance_record_id?: string;
          name?: string;
          file_url?: string;
          storage_path?: string | null;
          document_type?: 'budget' | 'invoice' | 'photo' | 'service_order' | 'report' | 'other';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      maintenance_parts: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          driver_id: string | null;
          trip_id: string | null;
          maintenance_record_id: string;
          name: string;
          code: string | null;
          quantity: number;
          unit_price: number;
          total_price: number;
          supplier: string | null;
          warranty_until: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          maintenance_record_id: string;
          name: string;
          code?: string | null;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          supplier?: string | null;
          warranty_until?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          maintenance_record_id?: string;
          name?: string;
          code?: string | null;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          supplier?: string | null;
          warranty_until?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      maintenance_services: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          driver_id: string | null;
          trip_id: string | null;
          maintenance_record_id: string;
          description: string;
          hours: number | null;
          amount: number;
          responsible: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          maintenance_record_id: string;
          description: string;
          hours?: number | null;
          amount?: number;
          responsible?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          driver_id?: string | null;
          trip_id?: string | null;
          maintenance_record_id?: string;
          description?: string;
          hours?: number | null;
          amount?: number;
          responsible?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      maintenance_schedules: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string;
          driver_id: string | null;
          trip_id: string | null;
          schedule_type: 'oil_change' | 'review' | 'preventive';
          alert_type: 'km' | 'date' | 'hour_meter';
          alert_km: number | null;
          alert_date: string | null;
          alert_hour_meter: number | null;
          last_done_at: string | null;
          next_due_at: string | null;
          last_odometer_km: number | null;
          last_hour_meter: number | null;
          is_active: boolean;
          notes: string | null;
          metadata: Json;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id: string;
          driver_id?: string | null;
          trip_id?: string | null;
          schedule_type: 'oil_change' | 'review' | 'preventive';
          alert_type: 'km' | 'date' | 'hour_meter';
          alert_km?: number | null;
          alert_date?: string | null;
          alert_hour_meter?: number | null;
          last_done_at?: string | null;
          next_due_at?: string | null;
          last_odometer_km?: number | null;
          last_hour_meter?: number | null;
          is_active?: boolean;
          notes?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string;
          driver_id?: string | null;
          trip_id?: string | null;
          schedule_type?: 'oil_change' | 'review' | 'preventive';
          alert_type?: 'km' | 'date' | 'hour_meter';
          alert_km?: number | null;
          alert_date?: string | null;
          alert_hour_meter?: number | null;
          last_done_at?: string | null;
          next_due_at?: string | null;
          last_odometer_km?: number | null;
          last_hour_meter?: number | null;
          is_active?: boolean;
          notes?: string | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      tires: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          maintenance_record_id: string | null;
          asset_number: string | null;
          internal_code: string | null;
          brand: string | null;
          model: string | null;
          tire_size: string | null;
          manufacturer: string | null;
          dot_number: string | null;
          fire_number: string | null;
          serial_number: string | null;
          expected_life_km: number | null;
          current_km: number;
          accumulated_km: number;
          purchase_date: string | null;
          purchase_value: number | null;
          supplier: string | null;
          warranty: string | null;
          tire_status: 'in_stock' | 'installed' | 'in_retread' | 'discarded' | 'warranty';
          current_position: 'front_left' | 'front_right' | 'rear_left_outer' | 'rear_left_inner' | 'rear_right_outer' | 'rear_right_inner' | 'spare' | 'other' | null;
          notes: string | null;
          recap_count: number;
          total_recap_cost: number;
          remaining_life_km: number | null;
          cost_per_km: number | null;
          last_tread_depth_mm: number | null;
          metadata: Json;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id: string | null;
          integration_source: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          asset_number?: string | null;
          internal_code?: string | null;
          brand?: string | null;
          model?: string | null;
          tire_size?: string | null;
          manufacturer?: string | null;
          dot_number?: string | null;
          fire_number?: string | null;
          serial_number?: string | null;
          expected_life_km?: number | null;
          current_km?: number;
          accumulated_km?: number;
          purchase_date?: string | null;
          purchase_value?: number | null;
          supplier?: string | null;
          warranty?: string | null;
          tire_status?: 'in_stock' | 'installed' | 'in_retread' | 'discarded' | 'warranty';
          current_position?: 'front_left' | 'front_right' | 'rear_left_outer' | 'rear_left_inner' | 'rear_right_outer' | 'rear_right_inner' | 'spare' | 'other' | null;
          notes?: string | null;
          recap_count?: number;
          total_recap_cost?: number;
          remaining_life_km?: number | null;
          cost_per_km?: number | null;
          last_tread_depth_mm?: number | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          asset_number?: string | null;
          internal_code?: string | null;
          brand?: string | null;
          model?: string | null;
          tire_size?: string | null;
          manufacturer?: string | null;
          dot_number?: string | null;
          fire_number?: string | null;
          serial_number?: string | null;
          expected_life_km?: number | null;
          current_km?: number;
          accumulated_km?: number;
          purchase_date?: string | null;
          purchase_value?: number | null;
          supplier?: string | null;
          warranty?: string | null;
          tire_status?: 'in_stock' | 'installed' | 'in_retread' | 'discarded' | 'warranty';
          current_position?: 'front_left' | 'front_right' | 'rear_left_outer' | 'rear_left_inner' | 'rear_right_outer' | 'rear_right_inner' | 'spare' | 'other' | null;
          notes?: string | null;
          recap_count?: number;
          total_recap_cost?: number;
          remaining_life_km?: number | null;
          cost_per_km?: number | null;
          last_tread_depth_mm?: number | null;
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      tire_history: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          maintenance_record_id: string | null;
          tire_id: string;
          action: string;
          changes: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          tire_id: string;
          action: string;
          changes?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          tire_id?: string;
          action?: string;
          changes?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      tire_movements: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          maintenance_record_id: string | null;
          tire_id: string;
          movement_type: 'install' | 'remove' | 'position_change' | 'rotation';
          position: 'front_left' | 'front_right' | 'rear_left_outer' | 'rear_left_inner' | 'rear_right_outer' | 'rear_right_inner' | 'spare' | 'other' | null;
          installed_at: string | null;
          removed_at: string | null;
          reason: string | null;
          responsible: string | null;
          odometer_km: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          tire_id: string;
          movement_type: 'install' | 'remove' | 'position_change' | 'rotation';
          position?: 'front_left' | 'front_right' | 'rear_left_outer' | 'rear_left_inner' | 'rear_right_outer' | 'rear_right_inner' | 'spare' | 'other' | null;
          installed_at?: string | null;
          removed_at?: string | null;
          reason?: string | null;
          responsible?: string | null;
          odometer_km?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          tire_id?: string;
          movement_type?: 'install' | 'remove' | 'position_change' | 'rotation';
          position?: 'front_left' | 'front_right' | 'rear_left_outer' | 'rear_left_inner' | 'rear_right_outer' | 'rear_right_inner' | 'spare' | 'other' | null;
          installed_at?: string | null;
          removed_at?: string | null;
          reason?: string | null;
          responsible?: string | null;
          odometer_km?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      tire_inspections: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          maintenance_record_id: string | null;
          tire_id: string;
          tread_depth_mm: number | null;
          pressure_psi: number | null;
          wear_level: 'good' | 'warning' | 'critical' | null;
          inspected_at: string;
          responsible: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          tire_id: string;
          tread_depth_mm?: number | null;
          pressure_psi?: number | null;
          wear_level?: 'good' | 'warning' | 'critical' | null;
          inspected_at?: string;
          responsible?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          tire_id?: string;
          tread_depth_mm?: number | null;
          pressure_psi?: number | null;
          wear_level?: 'good' | 'warning' | 'critical' | null;
          inspected_at?: string;
          responsible?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      tire_recaps: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          maintenance_record_id: string | null;
          tire_id: string;
          supplier: string | null;
          recap_number: string | null;
          amount: number | null;
          odometer_km: number | null;
          recapped_at: string;
          warranty: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          tire_id: string;
          supplier?: string | null;
          recap_number?: string | null;
          amount?: number | null;
          odometer_km?: number | null;
          recapped_at?: string;
          warranty?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          tire_id?: string;
          supplier?: string | null;
          recap_number?: string | null;
          amount?: number | null;
          odometer_km?: number | null;
          recapped_at?: string;
          warranty?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      tire_documents: {
        Row: {
          id: string;
          company_id: string;
          branch_id: string | null;
          vehicle_id: string | null;
          maintenance_record_id: string | null;
          tire_id: string;
          name: string;
          file_url: string;
          storage_path: string | null;
          document_type: 'invoice' | 'warranty' | 'photo' | 'report' | 'other';
          mime_type: string | null;
          file_size: number | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          tire_id: string;
          name: string;
          file_url: string;
          storage_path?: string | null;
          document_type?: 'invoice' | 'warranty' | 'photo' | 'report' | 'other';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          branch_id?: string | null;
          vehicle_id?: string | null;
          maintenance_record_id?: string | null;
          tire_id?: string;
          name?: string;
          file_url?: string;
          storage_path?: string | null;
          document_type?: 'invoice' | 'warranty' | 'photo' | 'report' | 'other';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      routes: {
        Row: {
          id: string;
          company_id: string;
          name: string;
          code: string | null;
          origin: string;
          destination: string;
          route_type: 'delivery' | 'pickup' | 'transfer' | 'distribution' | 'other';
          planned_distance_km: number | null;
          lead_time_minutes: number | null;
          unload_time_minutes: number | null;
          notes: string | null;
          operational_status: 'active' | 'inactive';
          metadata: Json;
          status: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id: string | null;
          integration_source: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          name: string;
          code?: string | null;
          origin: string;
          destination: string;
          route_type?: 'delivery' | 'pickup' | 'transfer' | 'distribution' | 'other';
          planned_distance_km?: number | null;
          lead_time_minutes?: number | null;
          unload_time_minutes?: number | null;
          notes?: string | null;
          operational_status?: 'active' | 'inactive';
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          name?: string;
          code?: string | null;
          origin?: string;
          destination?: string;
          route_type?: 'delivery' | 'pickup' | 'transfer' | 'distribution' | 'other';
          planned_distance_km?: number | null;
          lead_time_minutes?: number | null;
          unload_time_minutes?: number | null;
          notes?: string | null;
          operational_status?: 'active' | 'inactive';
          metadata?: Json;
          status?: 'active' | 'inactive' | 'blocked' | 'archived';
          external_id?: string | null;
          integration_source?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      route_history: {
        Row: {
          id: string;
          company_id: string;
          route_id: string;
          action: string;
          changes: Json;
          previous_operational_status: 'active' | 'inactive' | null;
          new_operational_status: 'active' | 'inactive' | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          route_id: string;
          action: string;
          changes?: Json;
          previous_operational_status?: 'active' | 'inactive' | null;
          new_operational_status?: 'active' | 'inactive' | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          route_id?: string;
          action?: string;
          changes?: Json;
          previous_operational_status?: 'active' | 'inactive' | null;
          new_operational_status?: 'active' | 'inactive' | null;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      route_documents: {
        Row: {
          id: string;
          company_id: string;
          route_id: string;
          name: string;
          file_url: string;
          storage_path: string | null;
          document_type: 'document' | 'map' | 'other';
          mime_type: string | null;
          file_size: number | null;
          created_at: string;
          deleted_at: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          route_id: string;
          name: string;
          file_url: string;
          storage_path?: string | null;
          document_type?: 'document' | 'map' | 'other';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          route_id?: string;
          name?: string;
          file_url?: string;
          storage_path?: string | null;
          document_type?: 'document' | 'map' | 'other';
          mime_type?: string | null;
          file_size?: number | null;
          created_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_plan_catalog: {
        Args: Record<string, never>;
        Returns: Json;
      };
      seed_default_roles_for_company: {
        Args: {
          p_company_id: string;
          p_created_by?: string | null;
        };
        Returns: undefined;
      };
      company_has_active_members: {
        Args: {
          p_company_id: string;
        };
        Returns: boolean;
      };
      get_my_company_ids: {
        Args: Record<string, never>;
        Returns: string[];
      };
      is_company_member: {
        Args: {
          p_company_id: string;
        };
        Returns: boolean;
      };
      has_company_permission: {
        Args: {
          p_company_id: string;
          p_permission_code: string;
        };
        Returns: boolean;
      };
      is_company_super_admin: {
        Args: {
          p_company_id: string;
        };
        Returns: boolean;
      };
      get_my_portal_role: {
        Args: Record<string, never>;
        Returns: Database['public']['Enums']['portal_role'];
      };
      is_portal_owner: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      is_portal_user: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      update_company_provision_status: {
        Args: {
          p_company_id: string;
          p_status: Database['public']['Enums']['provision_status'];
          p_error?: string | null;
        };
        Returns: undefined;
      };
      complete_company_provisioning: {
        Args: {
          p_company_id: string;
          p_profile_id: string;
        };
        Returns: string;
      };
      get_vehicle_stats: {
        Args: {
          p_company_id: string;
        };
        Returns: Json;
      };
      get_driver_stats: {
        Args: {
          p_company_id: string;
        };
        Returns: Json;
      };
      generate_trip_number: {
        Args: {
          p_company_id: string;
        };
        Returns: string;
      };
      get_trip_stats: {
        Args: {
          p_company_id: string;
        };
        Returns: Json;
      };
      get_fuel_stats: {
        Args: {
          p_company_id: string;
        };
        Returns: Json;
      };
      get_maintenance_stats: {
        Args: {
          p_company_id: string;
        };
        Returns: Json;
      };
      get_tire_stats: {
        Args: {
          p_company_id: string;
        };
        Returns: Json;
      };
    };
    Enums: {
      entity_status: 'active' | 'inactive' | 'blocked' | 'archived';
      provision_status: 'pending' | 'in_progress' | 'completed' | 'error';
      portal_role: 'OWNER' | 'SUPPORT' | 'FINANCE';
      portal_audit_action: 'login' | 'logout' | 'company_create' | 'company_update' | 'company_provision' | 'company_delete' | 'password_reset' | 'user_create' | 'user_update' | 'user_role_change' | 'user_activate' | 'user_deactivate' | 'plan_change' | 'company_suspend' | 'company_reactivate' | 'settings_update';
      vehicle_asset_status: 'active' | 'maintenance' | 'inactive' | 'sold';
      vehicle_fuel_type: 'diesel' | 'gasoline' | 'ethanol' | 'flex' | 'gnv' | 'electric' | 'hybrid' | 'other';
      provider_name: 'openai' | 'google' | 'azure' | 'aws' | 'anthropic' | 'custom';
      kind: 'ocr' | 'image_analysis' | 'document_vision' | 'object_detection' | 'multimodal' | 'custom';
      driver_operational_status: 'active' | 'inactive';
      driver_license_category: 'A' | 'B' | 'C' | 'D' | 'E' | 'AB' | 'AC' | 'AD' | 'AE';
      driver_contract_type: 'clt' | 'pj' | 'autonomo' | 'agregado' | 'terceiro';
      driver_document_type: 'photo' | 'cnh_front' | 'cnh_back' | 'proof' | 'aso' | 'document';
      trip_status: 'planned' | 'scheduled' | 'loading' | 'in_progress' | 'delivering' | 'waiting' | 'completed' | 'cancelled' | 'returned';
      trip_document_type: 'cte' | 'mdfe' | 'nfe' | 'canhoto' | 'photo' | 'receipt' | 'checklist' | 'other';
      trip_occurrence_type: 'delay' | 'breakdown' | 'accident' | 'fine' | 'redelivery' | 'return' | 'missing_document' | 'other';
      trip_expense_type: 'toll' | 'food' | 'lodging' | 'tire_shop' | 'maintenance' | 'other';
      fuel_document_type: 'invoice' | 'receipt' | 'proof' | 'pump_photo' | 'other';
      fuel_inconsistency_flag: 'odometer_decrease' | 'odometer_missing' | 'amount_mismatch' | 'consumption_outlier' | 'future_date' | 'duplicate_same_day';
      maintenance_type: 'preventive' | 'corrective' | 'emergency' | 'warranty' | 'review' | 'oil_change' | 'brakes' | 'suspension' | 'engine' | 'electrical' | 'cooling' | 'transmission' | 'tires' | 'other';
      maintenance_priority: 'low' | 'medium' | 'high' | 'critical';
      maintenance_status: 'open' | 'in_progress' | 'waiting_parts' | 'completed' | 'cancelled';
      maintenance_document_type: 'budget' | 'invoice' | 'photo' | 'service_order' | 'report' | 'other';
      maintenance_schedule_type: 'oil_change' | 'review' | 'preventive';
      maintenance_alert_type: 'km' | 'date' | 'hour_meter';
      tire_status: 'in_stock' | 'installed' | 'in_retread' | 'discarded' | 'warranty';
      tire_position: 'front_left' | 'front_right' | 'rear_left_outer' | 'rear_left_inner' | 'rear_right_outer' | 'rear_right_inner' | 'spare' | 'other';
      tire_movement_type: 'install' | 'remove' | 'position_change' | 'rotation';
      tire_document_type: 'invoice' | 'warranty' | 'photo' | 'report' | 'other';
      tire_wear_level: 'good' | 'warning' | 'critical';
      route_operational_status: 'active' | 'inactive';
      route_type: 'delivery' | 'pickup' | 'transfer' | 'distribution' | 'other';
      route_document_type: 'document' | 'map' | 'other';
    };
    CompositeTypes: Record<string, never>;
  };
};
