import {
  AlertTriangle,
  Calendar,
  Car,
  CircleDot,
  DollarSign,
  FileText,
  Fuel,
  Gauge,
  IdCard,
  MapPin,
  Percent,
  Plus,
  TrendingDown,
  TrendingUp,
  Truck,
  UserCheck,
  UserX,
  Wallet,
  Wrench,
} from 'lucide-react';

export const kpiIcons = {
  'clientes-total': FileText,
  'clientes-ativos': FileText,
  'clientes-inativos': FileText,
  'contratos-ativos': FileText,
  'contratos-vencendo': FileText,
  'receita-contratada': DollarSign,
  'veiculos-total': Truck,
  'veiculos-ativos': Truck,
  'veiculos-manutencao': Wrench,
  'veiculos-inativos': Truck,
  'veiculos-km-media': Gauge,
  'motoristas-total': Car,
  'motoristas-ativos': UserCheck,
  'motoristas-inativos': UserX,
  'motoristas-cnh-vencendo': IdCard,
  'motoristas-cnh-vencidas': AlertTriangle,
  'motoristas-ear-pendente': IdCard,
  'viagens-total': MapPin,
  'viagens-em-andamento': MapPin,
  'viagens-concluidas': MapPin,
  'viagens-canceladas': MapPin,
  'viagens-tempo-medio': Gauge,
  'viagens-km-rodados': Gauge,
  'viagens-motoristas': UserCheck,
  'viagens-veiculos': Truck,
  'viagens-ocorrencias': AlertTriangle,
  'viagens-entregas': MapPin,
  'abastecimentos-total': Fuel,
  'abastecimentos-litros': Fuel,
  'abastecimentos-valor': DollarSign,
  'abastecimentos-preco-medio': DollarSign,
  'abastecimentos-consumo': Gauge,
  'abastecimentos-km-l': Gauge,
  'abastecimentos-veiculo-economico': Truck,
  'abastecimentos-veiculo-gasto': Truck,
  'abastecimentos-motorista-economico': UserCheck,
  'abastecimentos-motorista-gasto': UserX,
  'abastecimentos-inconsistentes': AlertTriangle,
  'pneus-total': CircleDot,
  'pneus-instalados': CircleDot,
  'pneus-estoque': CircleDot,
  'pneus-descartados': CircleDot,
  'pneus-recapados': CircleDot,
  'pneus-km-medio': Gauge,
  'pneus-custo-km': DollarSign,
  'pneus-troca-proxima': AlertTriangle,
  'manutencoes-total': Wrench,
  'manutencoes-preventivas': Wrench,
  'manutencoes-correctivas': Wrench,
  'manutencoes-emergencia': AlertTriangle,
  'manutencoes-custo-total': DollarSign,
  'manutencoes-tempo-parado': Gauge,
  'manutencoes-veiculos-indisponiveis': Truck,
  'manutencoes-agendamentos-atrasados': Calendar,
  receita: DollarSign,
  lucro: TrendingUp,
  'fluxo-caixa': Wallet,
  ebitda: TrendingUp,
  margem: Percent,
  'custo-km': TrendingDown,
  'receita-km': DollarSign,
  'lucro-km': TrendingUp,
} as const;
