export {
  createCustomerAction,
  createCustomerAddressAction,
  createCustomerContactAction,
  createCustomerContractAction,
  deleteCustomerAction,
  deleteCustomerAddressAction,
  deleteCustomerContactAction,
  deleteCustomerContractAction,
  deleteCustomerDocumentAction,
  registerCustomerFileAction,
  resolveContractFreightAction,
  updateCustomerAction,
  updateCustomerAddressAction,
  updateCustomerContactAction,
  updateCustomerContractAction,
  updateCustomerStatusAction,
  replaceCustomerDocumentAction,
} from './customer-actions';
